# Generated by Django 4.2.1 on 2023-05-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=122)),
                ('mobilenumber', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=45)),
                ('birthdate', models.DateField()),
            ],
        ),
    ]
