# Generated by Django 4.2.1 on 2023-05-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
    ]
