# Generated by Django 4.2.1 on 2023-05-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
